GCC=clang-7
CFLAGS=-g -ansi -pedantic -Wall -no-pie -pg

goodbye: goodbye.c
	$(GCC) $(CFLAGS) -o goodbye goodbye.c -lncurses

add1: add1.c
	$(GCC) $(CFLAGS) -o add1 add1.c -lncurses

add2: add2.c
	$(GCC) $(CFLAGS) -o add2 add2.c -lncurses

add3: add3.c
	$(GCC) $(CFLAGS) -o add3 add3.c -lncurses

yoda: yoda.c
	$(GCC) $(CFLAGS) -o yoda yoda.c -lncurses

typewriter: typewriter.c
	$(GCC) $(CFLAGS) -o typewriter typewriter.c -lncurses

yourname: yourname.c
	$(GCC) $(CFLAGS) -o yourname yourname.c -lncurses

twinkle: twinkle.c
	$(GCC) $(CFLAGS) -o twinkle twinkle.c -lncurses

annoy: annoy.c
	$(GCC) $(CFLAGS) -o annoy annoy.c -lncurses

colortest: colortest.c
	$(GCC) $(CFLAGS) -o colortest colortest.c -lncurses

yellowred: yellowred.c
	$(GCC) $(CFLAGS) -o yellowred yellowred.c -lncurses

colorful: colorful.c
	$(GCC) $(CFLAGS) -o colorful colorful.c -lncurses

pink: pink.c
	$(GCC) $(CFLAGS) -o pink pink.c -lncurses

bgcolor1: bgcolor1.c
	$(GCC) $(CFLAGS) -o bgcolor1 bgcolor1.c -lncurses

bgcolor2: bgcolor2.c
	$(GCC) $(CFLAGS) -o bgcolor2 bgcolor2.c -lncurses

attrtest: attrtest.c
	$(GCC) $(CFLAGS) -o attrtest attrtest.c -lncurses

pi: pi.c
	$(GCC) $(CFLAGS) -o pi pi.c -lncurses

acslist: acslist.c
	$(GCC) $(CFLAGS) -o acslist acslist.c -lncurses

clean:
	$(RM) *.o *.out add1 add2 add3 goodbye yoda typewriter
	$(RM) yourname twinkle annoy colortest yellowred colorful
	$(RM) pink bgcolor1 bgcolor2 attrtest pi acslist

